### PR TITLE
Bug fix with the ID string rendering in HTML

### PR DESCRIPTION
**Pull request by chrisvidal**

### CODE REVIEW

**Comment by artistro08** [comment]
Nice catch! Thank you!

**Comment by artistro08** [comment]
I actually just realized that this is supposed to be there. since the ID needs quotes, it needs to have them before and after the variable. These are automatically generated in chrome, but not in other browsers, so it would cause an error.

**Comment by artistro08** [comment]
nevermind, not sure why it does that. Just fixed it in again

**Comment by chrisvidal** [comment]
weird behavior indeed.
maybe need to replace the ' with "

**Comment by artistro08** [comment]
That may be it, I'll adjust in the next release. Thanks again!

**Pull request merged**
